version: '3'
services:
  tiler:
    image: rub21/tiler_benchmark:v2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
        - ./:/app
